### ISSUE TITLE
Instructions in README are for a different repo

### ISSUE THREAD

**Issue by cponder** [ESCOMP/EarthWorks#1]
These instructions in the README.md file
```
git clone https://github.com/dazlich/earthworks.git
cd earthworks
./manage_externals/checkout_externals -v
```
look like they ought to say
```
git clone git@github.com:ESCOMP/EarthWorks.git
```
Is this correct?

**Comment by dazlich** [comment]
That would be something we failed to update, correct.

The correct one would be EarthWorksOrg rather than ESCOMP.

Sent from my iPhone

On Mar 9, 2023, at 6:46 AM, Carl Ponder ***@***.***> wrote:

﻿

** Caution: EXTERNAL Sender **

These instructions in the README.md file

git clone https://github.com/dazlich/earthworks.git
cd earthworks
./manage_externals/checkout_externals -v


look like they ought to say

git clone ***@***.***:ESCOMP/EarthWorks.git


Is this correct?

**Comment by gdicker1** [comment]
This isn't the correct repo for EarthWorks development. Use [EarthWorksOrg/EarthWorks](https://github.com/EarthWorksOrg/EarthWorks) and particularly the release-ew1.0 tag
